-- Enable Row Level Security (RLS) recommended, but for now we'll keep it simple for a prototype
-- You might want to enable RLS and add policies for authenticated users later.

-- 1. Create 'tiles' table
create table public.tiles (
  id bigint generated by default as identity primary key,
  label text not null,
  image_url text, -- Can be null if emoji is present
  emoji text,
  category text default 'General',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  usage_count bigint default 0,
  is_system boolean default false
);

-- 2. Create 'health_logs' table
create table public.health_logs (
  id bigint generated by default as identity primary key,
  bpm integer,
  spo2 integer,
  systolic integer,
  diastolic integer,
  timestamp timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Storage Bucket Setup
-- Ensure a bucket named 'communication-tiles' exists.

-- SEED DATA: Insert default tiles if they don't exist
-- Copy and run this block to seed your database with permanent tiles.
-- You can run this multiple times; it uses ON CONFLICT DO NOTHING if you set a unique constraint,
-- but for simplicity, we'll just check existence or user can clear table first.

/*
INSERT INTO public.tiles (label, emoji, category, is_system, image_url) VALUES
('Breakfast', '🥞', 'Morning', true, ''),
('Toilet', '🚽', 'Morning', true, ''),
('Lunch', '🥙', 'Day', true, ''),
('Living Room', '🛋️', 'Day', true, ''),
('Dinner', '🍽️', 'Night', true, ''),
('Bedroom', '🛏️', 'Night', true, ''),
('Sleep', '😴', 'Night', true, ''),
('Yes', '✅', 'General', true, ''),
('No', '❌', 'General', true, ''),
('Stop', '✋', 'General', true, ''),
('Help', '🆘', 'General', true, '');
*/
